### PR TITLE
refactor!: update active-model using `JSON::Serializable`

### PR DESCRIPTION
**Pull request by caspiano**
Thanks @dukeraphaelng!

### CODE REVIEW

**Comment by dukenguyenxyz** [comment]
Currently throwing the following compiler

```
Error: can't annotate @id in RethinkORM::Lock because it was first defined in RethinkORM::Base
```

This is due to the following breaking change in 0.36.0
https://github.com/crystal-lang/crystal/pull/9502

**Comment by dukenguyenxyz** [comment]
I have no idea why `name_was` is getting serialised https://travis-ci.org/github/spider-gazelle/rethinkdb-orm/builds/764191628#L255-L264

All specs even the _was related one passed on active-model branch https://github.com/spider-gazelle/active-model/tree/json_yaml

`@{{name}}_was` is declared twice, [here](https://github.com/spider-gazelle/active-model/blob/8d23dee243b00625b92716f1cc9a4ce677570645/src/active-model/model.cr#L188-L194) and [here](https://github.com/spider-gazelle/active-model/blob/8d23dee243b00625b92716f1cc9a4ce677570645/src/active-model/model.cr#L248), and in the second one, JSON annotation is not present, however I cannot add the annotation there, the compiler yells that I cannot annotate an inherited instance_var

@caspiano

**Comment by caspiano** [comment]
@kimburgess @dukeraphaelng 
There seems to be an issue with redefining annotations when inheriting a model that has defined an attribute. Any ideas?

**Comment by dukenguyenxyz** [comment]
@caspiano  as mentioned above, this is due to https://github.com/spider-gazelle/rethinkdb-orm/pull/21#issuecomment-782791469

**Pull request merged**
