### PR TITLE
Add 'foreign_key_type' to association macros

### PR DESCRIPTION
**Pull request by watzon**
Trying to create an association in which the foreign key was anything other than a String was failing, so this fixes that by allowing users to set a `foreign_key_type` where appropriate. Ideally it would be nice to have this be done automagically, but idk if that's possible currently.

### CODE REVIEW

**Comment by watzon** [comment]
Converted to a draft because I'm still working on this. I came to the realization that associations are pretty broken in their current state, and if the goal is to be a bit more like Rails we're still a long way off. So far I have managed to get `has_one` associations to accept a `foreign_key`, `foreign_type`, and `primary_key` as well as having the method name be defined as a part of the type declaration at the beginning. So a `has_one` association would now look like this:

```crystal
# Example from my current project. `foreign_key` is technically unnecessary here as it's inferred from the method name.
has_one log_channel : Chat, primary_key: "chat_id", foreign_key: "log_channel_id", foreign_type: Int64
```

Let me know if you have any thoughts @caspiano

**Comment by caspiano** [comment]
Thanks for the contributions so far, they all look pretty good! I really like the refactor to the collection.

**Comment by watzon** [comment]
I've got a lot more incoming. I've just kind of been working on changes as I use RethinkORM in a project I'm working on. At this point it's a full refactor of several systems, so I probably need to rename the PR.

**Comment by caspiano** [comment]
Oh awesome!!! Your work is highly appreciated 😃

**Pull request closed without merging**
